version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    commands:
      - npm install -g @angular/cli@16.2.6
      - node --version
      - npm install
  build:
    commands:
      - ng build --configuration=$ENV
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/myapp'
